ordomatic/apps/accounts/urls.py
""" apps/accounts/urls.py """

from django.urls import path

from . import views as accounts_views

app_name = 'accounts'
urlpatterns = [
    path('signup/', accounts_views.signup, name='signup'),
    path('login/', accounts_views.Login.as_view(), name='login'),
    path('logout/', accounts_views.Logout.as_view(), name='logout'),
    path('details/', accounts_views.details, name='details'),
    path('update/', accounts_views.update, name='update'),
    path('change_password/', accounts_views.ChangePassword.as_view(),
         name='change_password'),
    path('change_password/done/', accounts_views.change_password_done,
         name='change_password_done'),
    path('reset_password/', accounts_views.ResetPassword.as_view(),
         name='reset_password'),
    path('reset_password_done/', accounts_views.reset_password_done,
         name='reset_password_done'),
    path('reset/<uidb64>/<token>/', accounts_views.PasswordResetConfirm.as_view(),
         name='reset_password_confirm'),
    path('reset/done/', accounts_views.reset_password_complete,
         name='reset_password_complete'),
]

ordomatic/apps/calendars/urls.py
""" apps/calendars/urls.py """

from django.urls import path

from . import views

app_name = 'calendars'
urlpatterns = [
    path('', views.calendars_list, name='calendars_list'),
    path('create/', views.calendar_create, name='calendar_create'),
    path('<int:pk>/', views.calendar_details, name='calendar_details'),
    path('<int:pk>/update/', views.calendar_update, name='calendar_update'),
    path('<int:pk>/delete/', views.calendar_delete, name='calendar_delete'),
]

ordomatic/apps/docs/urls.py
""" apps/docs/urls.py """

from django.urls import path

from . import views

app_name = 'docs'
urlpatterns = [
    path('', views.index, name='index'),
    path('overview/', views.overview, name='overview'),
    path('what_is_an_ordo/', views.what_is_an_ordo, name='what_is_an_ordo'),
    path('create_an_account/', views.create_an_account, name='create_an_account'),
    path('create_a_calendar/', views.create_a_calendar, name='create_a_calendar'),
    path('populate_your_calendar/', views.populate_your_calendar,
         name='populate_your_calendar'),
    path('create_an_ordo/', views.create_an_ordo, name='create_an_ordo'),
    path('for_developers/', views.for_developers, name='for_developers'),
]

ordomatic/apps/main/urls.py
""" apps/main/urls.py """

from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('ordo/', views.ordo, name='ordo'),
    path('get_ordo_as_html/<int:calendar>/<int:year>/',
         views.get_ordo_as_html, name='get_ordo_as_html'),
]

ordomatic/ordomatic/urls.py
""" ordomatic/urls.py """

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('ordomatic/', include('apps.main.urls')),
    path('ordomatic/docs/', include('apps.docs.urls')),
    path('ordomatic/accounts/', include('apps.accounts.urls')),
    path('ordomatic/calendars/', include('apps.calendars.urls')),
    path('ordomatic/days/', include('apps.days.urls')),
    path('ordomatic/admin/', admin.site.urls),
]

ordomatic/apps/main/views.py
""" apps/main/views.py """

from datetime import date
from django.contrib.auth.models import User

from django.shortcuts import render

from apps.calendars.models import Calendar
from apps.days.views import fetch_days


def home(request):
    """ Home page of Ordomatic. """
    return render(
        request,
        'main/home.html',
        {},
    )


def ordo(request):
    """ Ordo page of Ordomatic. """
    calendars = Calendar.objects \
        .filter(
            owner=User.objects.filter(username='Universal')
            .get()
        )
    # TODO: add all the public calendars of other users.
    if str(request.user) != 'AnonymousUser':
        calendars_owner = Calendar.objects.filter(
            owner=request.user).order_by('name')
        calendars = calendars_owner.union(calendars)
    return render(
        request,
        'main/ordo.html',
        {
            'calendars': calendars,
            'year': date.today().year,
        }
    )


def get_ordo_as_html(request, **kwargs):
    """ Returns the ordo of the given year as html. """
    days = fetch_days(kwargs['calendar'], kwargs['year'])

    return render(
        request,
        'main/ordo_block.html',
        {
            'calendar': kwargs['calendar'],
            'year': kwargs['year'],
            'days': days,
        }
    )

ordomatic/templates/main.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title>Ordomatic</title>
        <link rel="icon" href={% static 'img/ordomatic.png' %}>
        <link rel="stylesheet" href={% static 'js/jquery-ui-1.12.1/jquery-ui.min.css' %}>
        <link rel="stylesheet" href={% static 'css/fontawesome-free-5.15.1-web/css/all.min.css' %}>
        <link rel="stylesheet" href={% static 'css/bootstrap-4.0.0-dist/css/bootstrap.min.css' %}>
        <link rel="stylesheet" href={% static "css/tempusdominus-bootstrap-4.min.css" %}>
        <link rel="stylesheet/less" href={% static 'css/ordomatic.less' %}>
        {% block css %}{% endblock css %}

        <style>@font-face{font-family: "LucidaHW"; src: url("{% static 'fonts/TR Lucida Handwriting Italic.ttf' %}")}</style>
    </head>

    <body>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <div id="logo" class="col-3 mr-auto d-flex align-items-center">
                <a href={% url 'main:home' %}>
                    <span id="title" class="orange my-0">Ordomatic</span>
                </a>
            </div>

            {% block nav %}{% endblock nav %}
        </nav>

        <ol class="breadcrumb w-100">
            <div class="dropdown mr-3">
                <div class="dropdown">
                    <button class="dropdown-button fas fa-bars"></button>
                    <div class="dropdown-content p-2">
                        {% if user.is_authenticated %}
                            <a href={% url 'accounts:details' %} class="user font-weight-bold mb-2">
                                <span class="fas fa-user grey mr-2"></span>{{ user }}
                            </a>
                            <a href={% url 'calendars:calendars_list' %}>Manage your calendars</a>
                        {% endif %}

                        <a href={% url 'main:ordo' %}>Create an ordo</a>
                        <a href={% url 'docs:index' %}>Read the Docs</a>

                        {% if user.is_authenticated %}
                            <a href={% url 'accounts:logout' %}>Logout</a>
                        {% else %}
                            <a href={% url 'accounts:login' %}>Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>

            <li class="breadcrumb-item"><a href={% url 'main:home' %}><span class="fas fa-home"></span></a></li>
            {% block breadcrumbs %}
            {% endblock breadcrumbs %}
        </ol>

        <div id="content" class="d-flex">
            <div class="w-100 d-flex flex-column align-items-center mx-5 my-3">
                {% block content %}{% endblock content %}
            </div>
        </div>
    </body>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
    <script src="{% static 'css/bootstrap-4.0.0-dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/less.min.js' %}"></script>
    <script src="{% static 'js/ordomatic.js' %}"></script>
    {% block javascript %}{% endblock javascript %}
</html>