ordomatic/apps/accounts/urls.py
""" apps/accounts/urls.py """

from django.urls import path

from . import views as accounts_views

app_name = 'accounts'
urlpatterns = [
    path('signup/', accounts_views.signup, name='signup'),
    path('login/', accounts_views.Login.as_view(), name='login'),
    path('logout/', accounts_views.Logout.as_view(), name='logout'),
    path('details/', accounts_views.details, name='details'),
    path('update/', accounts_views.update, name='update'),
    path('change_password/', accounts_views.ChangePassword.as_view(),
         name='change_password'),
    path('change_password/done/', accounts_views.change_password_done,
         name='change_password_done'),
    path('reset_password/', accounts_views.ResetPassword.as_view(),
         name='reset_password'),
    path('reset_password_done/', accounts_views.reset_password_done,
         name='reset_password_done'),
    path('reset/<uidb64>/<token>/', accounts_views.PasswordResetConfirm.as_view(),
         name='reset_password_confirm'),
    path('reset/done/', accounts_views.reset_password_complete,
         name='reset_password_complete'),
]

ordomatic/apps/accounts/views.py
""" apps/accounts/views.py """

from django.contrib.auth import authenticate, login
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import PasswordChangeView, PasswordResetConfirmView, PasswordResetView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy


def signup(request):
    """ Signup view. """
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return HttpResponseRedirect(reverse('main:home'))

    else:
        form = UserCreationForm()

    return render(
        request,
        'accounts/signup.html',
        {
            'form': form,
        },
    )


class Login(auth_views.LoginView):
    """ Login view. """
    template_name = 'accounts/login.html'


class Logout(auth_views.LogoutView):
    """ Logout view. """


@login_required
def details(request):
    """ Details view. """
    return render(
        request,
        'accounts/details.html',
    )


@login_required
def update(request):
    """ Update view. """
    return render(
        request,
        'accounts/update.html',
    )


class ChangePassword(PasswordChangeView):
    """ Change password view. """
    template_name = 'accounts/change_password.html'
    success_url = reverse_lazy('accounts:change_password_done')


def change_password_done(request):
    """ Change password done view. """
    return render(
        request,
        'accounts/change_password_done.html',
    )


class ResetPassword(PasswordResetView):
    """ Reset password view. """
    template_name = 'accounts/reset_password.html'
    email_template_name = 'accounts/reset_password_email.html'
    success_url = reverse_lazy('accounts:reset_password_done')


def reset_password_done(request):
    """ Reset password done view."""
    return render(
        request,
        'accounts/reset_password_done.html',
    )


class PasswordResetConfirm(PasswordResetConfirmView):
    """ Reset password confirm view. """
    template_name = 'accounts/reset_password_confirm.html'
    success_url = reverse_lazy('accounts:reset_password_complete')


def reset_password_complete(request):
    """ Reset password complete view. """
    return render(
        request,
        'accounts/reset_password_complete.html',
    )

ordomatic/apps/accounts/templates/accounts/change_password.html
{% extends 'main.html' %}

{% load widget_tweaks %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'accounts:details' %}>My account</a></li>
    <li class="breadcrumb-item active">Password change</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Change your password</h2>

    <form class="d-flex flex-column align-items-center w-100 mb-3" method="post" novalidate>
        <div class="col-6">
            {% csrf_token %}

            <!-- Old password -->
            <div class="form-group">
                {{ form.old_password.label_tag }}

                {% if form.is_bound %}
                    {% if form.old_password.errors %}
                        {% render_field form.old_password class="form-control is-invalid" %}
                        {% for error in form.old_password.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.old_password class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.old_password class="form-control" %}
                {% endif %}

                {% if form.old_password.help_text %}
                    <small class="form-text text-muted">
                        {{ form.old_password.help_text }}
                    </small>
                {% endif %}
            </div>

            <!-- New password 1 -->
            <div class="form-group">
                {{ form.new_password1.label_tag }}

                {% if form.is_bound %}
                    {% if form.new_password1.errors %}
                        {% render_field form.new_password1 class="form-control is-invalid" %}
                        {% for error in form.new_password1.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.new_password1 class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.new_password1 class="form-control" %}
                {% endif %}

                {% if form.new_password1.help_text %}
                    <small class="form-text text-muted">
                        {{ form.new_password1.help_text }}
                    </small>
                {% endif %}
            </div>

            <!-- New password 2 -->
            <div class="form-group">
                {{ form.new_password2.label_tag }}

                {% if form.is_bound %}
                    {% if form.new_password2.errors %}
                        {% render_field form.new_password2 class="form-control is-invalid" %}
                        {% for error in form.new_password2.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.new_password2 class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.new_password2 class="form-control" %}
                {% endif %}

                {% if form.new_password2.help_text %}
                    <small class="form-text text-muted">
                        {{ form.new_password2.help_text }}
                    </small>
                {% endif %}
            </div>
        </div>

        <div>
            <button type="submit" class="btn btn-primary">Validate</button>
        </div>
    </form>
{% endblock content %}

ordomatic/apps/accounts/templates/accounts/change_password_done.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active">Change password done</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2 class="mb-5">Your password has been updated with success!</h2>

    <a href={% url 'main:home' %} class="btn btn-primary">Back to home</a>
{% endblock content %}

ordomatic/apps/accounts/templates/accounts/details.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active">My account</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Details view</h2>
    <a href={% url 'accounts:update' %}>Modify your account</a>
    <a href={% url 'accounts:change_password' %}>Change your password</a>
    <a href={% url 'accounts:reset_password' %}>Reset your password</a>
{% endblock content %}

ordomatic/apps/accounts/templates/accounts/login.html
{% extends 'main.html' %}

{% load widget_tweaks %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active">Login</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Login!</h2>

    <form class="d-flex flex-column align-items-center w-100 mb-3" method="post" novalidate>
        <div class="col-4">
            {% csrf_token %}

            <!-- Username -->
            <div class="form-group">
                {{ form.username.label_tag }}
                {% render_field form.username class="form-control" %}
            </div>

            <!-- Password -->
            <div class="form-group">
                {{ form.password.label_tag }}
                {% render_field form.password class="form-control" %}
            </div>

            <!-- Non field errors -->
            {% if form.non_field_errors %}
                <div class="mb-4">
                    {% for error in form.non_field_errors %}
                        <div class='invalid-feedback red d-block'>
                            {{ error }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <!-- Validate -->
        <div class="mb-5">
            <button type="submit" class="btn btn-primary">Validate</button>
        </div>

        <div>
            No account yet? <a href={% url 'accounts:signup' %}>Create an account!</a>
        </div>
    </form>
{% endblock content %}

ordomatic/apps/accounts/templates/accounts/reset_password.html
{% extends 'main.html' %}

{% load widget_tweaks %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'accounts:details' %}>My account</a></li>
    <li class="breadcrumb-item active">Password reset</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Forgot your password?</h2>

    <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

    <form class="d-flex flex-column align-items-center w-100 mb-3" method="post" novalidate>
        <div class="col-6">
            {% csrf_token %}

            <div class="form-group">
                {{ form.email.label_tag }}

                {% if form.is_bound %}
                    {% if form.email.errors %}
                        {% render_field form.email class="form-control is-invalid" %}
                        {% for error in form.email.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.email class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.email class="form-control" %}
                {% endif %}

                {% if form.email.help_text %}
                    <small class="form-text text-muted">
                        {{ form.email.help_text }}
                    </small>
                {% endif %}
            </div>
        </div>

        <div>
            <button type="submit" class="btn btn-primary">Send me instructions!</button>
        </div>
    </form>
{% endblock content %}

ordomatic/apps/accounts/templates/accounts/reset_password_complete.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'accounts:details' %}>My account</a></li>
    <li class="breadcrumb-item active">Reset password complete</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Your password was reset successfuly!</h2>
{% endblock content %}

ordomatic/apps/accounts/templates/accounts/reset_password_confirm.html
{% extends 'main.html' %}

{% load widget_tweaks %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'accounts:details' %}>My account</a></li>
    <li class="breadcrumb-item active">Password change</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Change your password</h2>

    <form class="d-flex flex-column align-items-center w-100 mb-3" method="post" novalidate>
        <div class="col-6">
            {% csrf_token %}

            <!-- New password 1 -->
            <div class="form-group">
                {{ form.new_password1.label_tag }}

                {% if form.is_bound %}
                    {% if form.new_password1.errors %}
                        {% render_field form.new_password1 class="form-control is-invalid" %}
                        {% for error in form.new_password1.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.new_password1 class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.new_password1 class="form-control" %}
                {% endif %}

                {% if form.new_password1.help_text %}
                    <small class="form-text text-muted">
                        {{ form.new_password1.help_text }}
                    </small>
                {% endif %}
            </div>

            <!-- New password 2 -->
            <div class="form-group">
                {{ form.new_password2.label_tag }}

                {% if form.is_bound %}
                    {% if form.new_password2.errors %}
                        {% render_field form.new_password2 class="form-control is-invalid" %}
                        {% for error in form.new_password2.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.new_password2 class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.new_password2 class="form-control" %}
                {% endif %}

                {% if form.new_password2.help_text %}
                    <small class="form-text text-muted">
                        {{ form.new_password2.help_text }}
                    </small>
                {% endif %}
            </div>
        </div>

        <div>
            <button type="submit" class="btn btn-primary">Validate</button>
        </div>
    </form>
{% endblock content %}

ordomatic/apps/accounts/templates/accounts/reset_password_done.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'accounts:details' %}>My account</a></li>
    <li class="breadcrumb-item active">Password reset done</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Password reset fired!</h2>
    <h4>Check your inbox.</h4>
    
    <p>We've emailed you instructions for setting your password. You should receive the email shortly!</p>
{% endblock content %}

ordomatic/apps/accounts/templates/accounts/reset_password_email.html
You're receiving this email because you requested a password reset for your user account at http://brroman.pythonanywhere.com/ordomatic/.
Click on the link below to reset your password.
{{ protocol }}://{{ domain }}{% url 'accounts:reset_password_confirm' uidb64=uid token=token %}

ordomatic/apps/accounts/templates/accounts/signup.html
{% extends 'main.html' %}

{% load widget_tweaks %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active">Signup</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Create your account!</h2>

    <form class="d-flex flex-column align-items-center w-100 mb-3" method="post" novalidate>
        <div class="col-6">
            {% csrf_token %}

            <!-- Username -->
            <div class="form-group">
                {{ form.username.label_tag }}

                {% if form.is_bound %}
                    {% if form.username.errors %}
                        {% render_field form.username class="form-control is-invalid" %}
                        {% for error in form.username.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.username class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.username class="form-control" %}
                {% endif %}

                {% if form.username.help_text %}
                    <small class="form-text text-muted">
                        {{ form.username.help_text }}
                    </small>
                {% endif %}
            </div>

            <!-- Password 1 -->
            <div class="form-group">
                {{ form.password1.label_tag }}

                {% if form.is_bound %}
                    {% if form.password1.errors %}
                        {% render_field form.password1 class="form-control is-invalid" %}
                        {% for error in form.password1.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.password1 class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.password1 class="form-control" %}
                {% endif %}

                {% if form.password1.help_text %}
                    <small class="form-text text-muted">
                        {{ form.password1.help_text }}
                    </small>
                {% endif %}
            </div>

            <!-- Password 2 -->
            <div class="form-group">
                {{ form.password2.label_tag }}

                {% if form.is_bound %}
                    {% if form.password2.errors %}
                        {% render_field form.password2 class="form-control is-invalid" %}
                        {% for error in form.password2.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.password2 class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.password2 class="form-control" %}
                {% endif %}

                {% if form.password2.help_text %}
                    <small class="form-text text-muted">
                        {{ form.password2.help_text }}
                    </small>
                {% endif %}
            </div>
        </div>

        <div>
            <button type="submit" class="btn btn-primary">Validate</button>
        </div>
    </form>
{% endblock content %}

ordomatic/apps/accounts/templates/accounts/update.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'accounts:details' %}>My account</a></li>
    <li class="breadcrumb-item active">Update</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Update view</h2>
{% endblock content %}