ordomatic/apps/docs/urls.py
""" apps/docs/urls.py """

from django.urls import path

from . import views

app_name = 'docs'
urlpatterns = [
    path('', views.index, name='index'),
    path('overview/', views.overview, name='overview'),
    path('what_is_an_ordo/', views.what_is_an_ordo, name='what_is_an_ordo'),
    path('create_an_account/', views.create_an_account, name='create_an_account'),
    path('create_a_calendar/', views.create_a_calendar, name='create_a_calendar'),
    path('populate_your_calendar/', views.populate_your_calendar,
         name='populate_your_calendar'),
    path('create_an_ordo/', views.create_an_ordo, name='create_an_ordo'),
    path('for_developers/', views.for_developers, name='for_developers'),
]

ordomatic/apps/docs/views.py
from django.shortcuts import render


def index(request):
    """ 'Index' page of docs. """
    return render(
        request,
        'docs/index.html',
        {
            'pages': [
                {
                    'url': 'what_is_an_ordo',
                    'title': 'What is an ordo?',
                },
                {
                    'url': 'overview',
                    'title': 'Overview of Ordomatic',
                },
                {
                    'url': 'create_an_account',
                    'title': 'Create an account',
                },
                {
                    'url': 'create_a_calendar',
                    'title': 'Create a calendar',
                },
                {
                    'url': 'populate_your_calendar',
                    'title': 'Populate your calendar',
                },
                {
                    'url': 'create_an_ordo',
                    'title': 'Create an ordo!',
                },
                {
                    'url': 'for_developers',
                    'title': 'For developers',
                },
            ],
        }
    )


def overview(request):
    """ 'Overview' page of docs. """
    return render(request, 'docs/overview.html')


def what_is_an_ordo(request):
    """ 'What is an ordo?' page of docs. """
    return render(request, 'docs/what_is_an_ordo.html')


def create_an_account(request):
    """ 'Create an account' page of docs. """
    return render(request, 'docs/create_an_account.html')


def create_a_calendar(request):
    """ 'Create a calendar' page of docs. """
    return render(request, 'docs/create_a_calendar.html')


def populate_your_calendar(request):
    """ 'Populate your calendar' page of docs. """
    return render(request, 'docs/populate_your_calendar.html')


def create_an_ordo(request):
    """ 'Create an ordo' page of docs. """
    return render(request, 'docs/create_an_ordo.html')


def for_developers(request):
    """ 'For developers' page of docs. """
    return render(request, 'docs/for_developers.html')

ordomatic/apps/docs/templates/docs/create_a_calendar.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item "><a href={% url 'docs:index' %}>Docs</a></li>
    <li class="breadcrumb-item active">Create a calendar</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Create a calendar</h2>

    <div class="fs-10 col-8">
        <p>Here the text.</p>
    </div>

    <div class="d-flex align-content-between w-100 mt-5">
        <div class="col-5 d-flex justify-content-start">
            <p class="btn btn-primary text-left font-weight-bold">
                <a href={% url 'docs:create_an_account' %} class="text-white"><span class="fas fa-arrow-left mr-3"></span>Create an account
                </a>
            </p>
        </div>

        <div class="col-2 d-flex justify-content-center">
            <p class="text-center w-100">
                <a href={% url 'docs:index' %} class="btn btn-warning text-white font-weight-bold">Menu</a>
            </p>
        </div>

        <div class="col-5 d-flex justify-content-end">
            <p class="btn btn-primary text-right font-weight-bold">
                <a href={% url 'docs:populate_your_calendar' %} class="text-white">Populate your calendar<span class="fas fa-arrow-right ml-3"></span>
                </a>
            </p>
        </div>
    </div>
{% endblock content %}

ordomatic/apps/docs/templates/docs/create_an_account.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item "><a href={% url 'docs:index' %}>Docs</a></li>
    <li class="breadcrumb-item active">Create an account</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Create an account</h2>

    <div class="fs-10 col-8">
        <p>Here the text.</p>
    </div>

    <div class="d-flex align-content-between w-100 mt-5">
        <div class="col-5 d-flex justify-content-start">
            <p class="btn btn-primary text-left font-weight-bold">
                <a href={% url 'docs:overview' %} class="text-white"><span class="fas fa-arrow-left mr-3"></span>Overview of Ordomatic
                </a>
            </p>
        </div>

        <div class="col-2 d-flex justify-content-center">
            <p class="text-center w-100">
                <a href={% url 'docs:index' %} class="btn btn-warning text-white font-weight-bold">Menu</a>
            </p>
        </div>

        <div class="col-5 d-flex justify-content-end">
            <p class="btn btn-primary text-right font-weight-bold">
                <a href={% url 'docs:create_a_calendar' %} class="text-white">Create a calendar<span class="fas fa-arrow-right ml-3"></span>
                </a>
            </p>
        </div>
    </div>
{% endblock content %}

ordomatic/apps/docs/templates/docs/create_an_ordo.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item "><a href={% url 'docs:index' %}>Docs</a></li>
    <li class="breadcrumb-item active">Create an ordo</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Create an ordo!</h2>

    <div class="fs-10 col-8">
        <p>Here the text.</p>
    </div>

    <div class="d-flex align-content-between w-100 mt-5">
        <div class="col-5 d-flex justify-content-start">
            <p class="btn btn-primary text-left font-weight-bold">
                <a href={% url 'docs:populate_your_calendar' %} class="text-white"><span class="fas fa-arrow-left mr-3"></span>Populate your calendar
                </a>
            </p>
        </div>

        <div class="col-2 d-flex justify-content-center">
            <p class="text-center w-100">
                <a href={% url 'docs:index' %} class="btn btn-warning text-white font-weight-bold">Menu</a>
            </p>
        </div>

        <div class="col-5 d-flex justify-content-end">
            <p class="btn btn-primary text-right font-weight-bold">
                <a href={% url 'docs:for_developers' %} class="text-white">For developers<span class="fas fa-arrow-right ml-3"></span>
                </a>
            </p>
        </div>
    </div>
{% endblock content %}

ordomatic/apps/docs/templates/docs/for_developers.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item "><a href={% url 'docs:index' %}>Docs</a></li>
    <li class="breadcrumb-item active">For developpers</li>
{% endblock breadcrumbs %}

{% block content %}
    <h1>For developers</h1>
    <h6 class="mb-5">(Linux only for now)</h6>

    <div class="doc-page col-8">
        <h3 class="text-left font-weight-bold mt-5">How to run Ordomatic locally?</h3>

        <p>Required: <span class="highlight">git</span>, <span class="highlight">python3.7</span>, <span class="highlight">virtualenv</span>, <span class="highlight">pip</span> and <span class="highlight">MySQL</span>.</p>

        <div class="mt-3"><b>1.</b> In a terminal, cd into the directory in which you have chosen to install your Ordomatic, and hit:</div>

        <div class="terminal mt-3">
            git clone https://github.com/BrRoman/ordomatic ordomatic</br>
        </div>

        <div class="caution d-flex mt-3">
            <span class="col-1 fas fa-exclamation-circle"></span>
            <p class="col-11 mb-0">If you have made a fork of Ordomatic (see below: 'How to contribute to Ordomatic?'), then replace the url with the url of your fork.</p>
        </div>

        <div class="mt-5"><b>2.</b> Create a virtualenv in your repo, and install all the required Python packages in this virtualenv:</div>

        <div class="terminal mt-3">
            virtualenv -p python3.7 ordomatic</br>
            cd ordomatic</br>
            source bin/activate</br>
            pip install -r requirements.txt
        </div>
        
        <div class="mt-5"><b>3.</b> Edit the file <span>/ordomatic/ordomatic/ordomatic/settings.py</span>:</div>

        <ul>
            <li>At the line 25, replace the empty string by your secret key. You can generate this secret key online <a href="https://djecrety.ir">here</a>.</li>
            <li>In the block concerning the database, enter your username and your password.</li>
        </ul>

        <div class="mt-5"><b>4.</b> Create your MySQL database:</div>

        <div class="mt-0">
            <div class="ml-4 mt-2">1. In a mysql console:</div>
            <div class="terminal">
                >>> CREATE DATABASE ordomatic;</br>
                >>> exit;
            </div>

            <div class="ml-4 mt-2">2. Then in a terminal:</div>
            <div class="terminal">
                ./manage.py makemigrations</br>
                ./manage.py migrate
            </div>
        </div>

        <h3 class="text-left font-weight-bold mt-5">How to contribute to Ordomatic?</h3>

        <div>
            <div>Before all, make a fork of Ordomatic on github: go to <a href="https://github.com/BrRoman/ordomatic">https://github.com/BrRoman/ordomatic</a> and click on the button "Fork".</div>
            <div>This will make a copy of Ordomatic on your own account.</div>
            <div>Clone this copy to your computer with "git clone".</div>

            <div class="mt-3">Then edit the code on your local machine and <a href="https://github.com/BrRoman/ordomatic/pulls">make a pull request</a> on Github.</div>

            <div class="mt-3">You can submit an issue too, <a href="https://github.com/BrRoman/ordomatic/issues">here</a>.</div>

            <div class="mt-3">Every contribution will be welcome! You can improve the code, add a feature or correct the docs…</div>
        </div>
    </div>

    <div class="d-flex align-content-between w-100 mt-5">
        <div class="col-5 d-flex justify-content-start">
            <p class="btn btn-primary text-left font-weight-bold">
                <a href={% url 'docs:create_an_ordo' %} class="text-white"><span class="fas fa-arrow-left mr-3"></span>Create an ordo!
                </a>
            </p>
        </div>

        <div class="col-2 d-flex justify-content-center">
            <p class="text-center w-100">
                <a href={% url 'docs:index' %} class="btn btn-warning text-white font-weight-bold">Menu</a>
            </p>
        </div>

        <div class="col-5 d-flex justify-content-end">
        </div>
    </div>
{% endblock content %}

ordomatic/apps/docs/templates/docs/index.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active">Docs</li>
{% endblock breadcrumbs %}

{% block content %}
    <h1>Welcome to Ordomatic's docs!</h1>
    <i>Here you will find everything you need to master Ordomatic…</i>

    <div class="col-4 mt-4">
        {% for page in pages %}
            <div class="w-100 mb-2">
                <a href={% url 'docs:'|add:page.url %} style="font-size: 14pt;">
                    {{ forloop.counter }}. {{ page.title }}
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

ordomatic/apps/docs/templates/docs/populate_your_calendar.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item "><a href={% url 'docs:index' %}>Docs</a></li>
    <li class="breadcrumb-item active">Populate your calendar</li>
{% endblock breadcrumbs %}

{% block content %}
    <h2>Populate your calendar</h2>

    <div class="fs-10 col-8">
        <p>Here the text.</p>
    </div>

    <div class="d-flex align-content-between w-100 mt-5">
        <div class="col-5 d-flex justify-content-start">
            <p class="btn btn-primary text-left font-weight-bold">
                <a href={% url 'docs:create_a_calendar' %} class="text-white"><span class="fas fa-arrow-left mr-3"></span>Create a calendar
                </a>
            </p>
        </div>

        <div class="col-2 d-flex justify-content-center">
            <p class="text-center w-100">
                <a href={% url 'docs:index' %} class="btn btn-warning text-white font-weight-bold">Menu</a>
            </p>
        </div>

        <div class="col-5 d-flex justify-content-end">
            <p class="btn btn-primary text-right font-weight-bold">
                <a href={% url 'docs:create_an_ordo' %} class="text-white">Create an ordo!<span class="fas fa-arrow-right ml-3"></span>
                </a>
            </p>
        </div>
    </div>
{% endblock content %}

ordomatic/apps/docs/templates/docs/what_is_an_ordo.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item "><a href={% url 'docs:index' %}>Docs</a></li>
    <li class="breadcrumb-item active">What is an ordo?</li>
{% endblock breadcrumbs %}

{% block content %}
    <h1 class="mb-5">What is an ordo?</h1>

    <div class="doc-page col-8">
        <p>An ordo is a <b>liturgical calendar</b>.</p>

        <p>It indicates, for a particular community, diocese or for the Universal Church, what to celebrate each day of the liturgical year, and how.</p>

        <p>A liturgical year is the superposition of two calendars: the "Temporal" and the "Sanctoral".</p>

        <p>The <b>Sanctoral</b> is the easiest to understand: it is composed of the <u>fixed</u> feasts of Christ, Blessed Virgin and the Saints. For example, the feast of saint Joseph is always the 19 March.</p>

        <p>The <b>Temporal</b> is composed of the <u>mobile</u> feasts of the year: Easter depends of the cycle of the Moon, and thus happens at a variable date depending of the year. Hence, the date of the Wednesday of the Ashes will happen too at a variable date, for it is 46 days before Easter. And so for all the Lent time and the Easter time.</p>

        <p>So, for each day of the year, you will have at least one day of the Temporal (Advent time, Christmas time, Lent, Easter Time, Ordinary Time, Time after Pentecost, etc.), and often one (or more) days of the Sanctoral. The question is: "How do you determine which one to choose?"</p>

        <p>There are some rules. Some of them are quite simple, other are more complicated. But you can imagine each day of the Temporal or the Sanctoral as an element with a given <b>force</b> (10, 20, 30, etc.). For example, the feast of saint Joseph (19 March) has a force of 90. The Palm's Sunday has a force of 120. So if those days happen the same day, you will celebrate the Palm's Sunday (and accessoirement, the feast of saint Joseph, which can't be overwritten, will be celebrated after the Easter's octave, but it is another history).</p>
    </div>

    <div class="d-flex align-content-between w-100 mt-5">
        <div class="col-5 d-flex justify-content-start">
        </div>

        <div class="col-2 d-flex justify-content-center">
            <p class="text-center w-100">
                <a href={% url 'docs:index' %} class="btn btn-warning text-white font-weight-bold">Menu</a>
            </p>
        </div>

        <div class="col-5 d-flex justify-content-end">
            <p class="btn btn-primary text-right font-weight-bold">
                <a href={% url 'docs:overview' %} class="text-white">Overview of Ordomatic<span class="fas fa-arrow-right ml-3"></span>
                </a>
            </p>
        </div>
    </div>
{% endblock content %}