ordomatic/apps/days/urls.py
""" apps/main/urls.py """

from django.urls import path

from . import views

app_name = 'days'
urlpatterns = [
    path('<int:calendar>/', views.home, name='home'),
    path('<int:calendar>/<str:category>/', views.days_list, name='days_list'),
    path('<int:calendar>/<str:category>/create/',
         views.day_create, name='day_create'),
    path('<int:calendar>/<str:category>/<int:pk>/',
         views.day_details, name='day_details'),
    path('<int:calendar>/<str:category>/<int:pk>/update/',
         views.day_update, name='day_update'),
    path('<int:calendar>/<str:category>/<int:pk>/delete/',
         views.day_delete, name='day_delete'),
]

ordomatic/apps/days/templates/days/delete.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'calendars:calendars_list' %}>Calendars</a></li>
    <li class="breadcrumb-item"><a href={% url 'calendars:calendar_details' calendar.pk %}>{{ calendar }}</a></li>
    <li class="breadcrumb-item"><a href={% url 'days:home' calendar.pk %}>Days</a></li>
    <li class="breadcrumb-item"><a href={% url 'days:days_list' calendar.pk category %}>{{ category|title }}</a></li>
    <li class="breadcrumb-item"><a href={% url 'days:day_details' calendar.pk category day.pk %}>{{ day }}</a></li>
    <li class="breadcrumb-item active">Delete</li>
{% endblock breadcrumbs %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <h3 class="red font-weight-bold">Are you sure you want to delete this day?</h3>
        <h4 class="text-center mb-5">({{ day }})</h4>

        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-danger mx-3">Yes</button>
            <a href={% url 'days:day_details' calendar.pk category day.pk %} class="btn btn-primary mx-3">No</a>
        </div>
    </form>
{% endblock content %}

ordomatic/apps/days/templates/days/details.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'calendars:calendars_list' %}>Calendars</a></li>
    <li class="breadcrumb-item"><a href={% url 'calendars:calendar_details' calendar.pk %}>{{ calendar }}</a></li>
    <li class="breadcrumb-item"><a href={% url 'days:home' calendar.pk %}>Days</a></li>
    <li class="breadcrumb-item"><a href={% url 'days:days_list' calendar.pk category %}>{{ category|title }}</a></li>
    <li class="breadcrumb-item active">{{ day }}</li>
{% endblock breadcrumbs %}

{% block content %}
    <h3>Details of day {{ day.name }}</h3>

    {% if category == 'tempo' %}
        ({{ day.baseline }}{% if day.add >= 0 %}+{% endif %}{{ day.add }})
    {% else %}
        ({{ day }})
    {% endif %}

    <div class="col-6 mt-3">
        <table class="table table-sm table-borderless">
            <tr>
                <td class="col-2 font-weight-bold">Name:</td>
                <td class="col-10">{{ day.name }}</td>
            </tr>
            <tr>
                <td class="col-2 font-weight-bold">Header:</td>
                <td class="col-10">{{ day.header }}</td>
            </tr>
            <tr>
                <td class="col-2 font-weight-bold">Body:</td>
                <td class="col-10">{{ day.body }}</td>
            </tr>
            <tr>
                <td class="col-2 font-weight-bold">Force:</td>
                <td class="col-10">{{ day.force }}</td>
            </tr>
        </table>
    </div>

    <a href={% url 'days:day_update' calendar.pk category day.pk%}>Edit this day</a>
    <a href={% url 'days:day_delete' calendar.pk category day.pk%}>Delete this day</a>
    <a href={% url 'days:days_list' calendar.pk category %}>Back to list</a>
{% endblock content %}

ordomatic/apps/days/templates/days/form.html
{% extends 'main.html' %}

{% load widget_tweaks %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'calendars:calendars_list' %}>Calendars</a></li>
    <li class="breadcrumb-item"><a href={% url 'calendars:calendar_details' calendar.pk %}>{{ calendar }}</a></li>
    <li class="breadcrumb-item"><a href={% url 'days:home' calendar.pk %}>Days</a></li>
    <li class="breadcrumb-item"><a href={% url 'days:days_list' calendar.pk category %}>{{ category|title }}</a></li>
    {% if day %}
        <li class="breadcrumb-item"><a href={% url 'days:day_details' calendar.pk category day.pk %}>{{ day }}</a></li>
        <li class="breadcrumb-item active">Update</li>
    {% else %}
        <li class="breadcrumb-item active">Create</li>
    {% endif %}
{% endblock breadcrumbs %}

{% block content %}
    {% if day %}
        <h3>Update {{ day }} ({{ category }})</h3>
    {% else %}
        <h3>Create a new day ({{ category }})</h3>
    {% endif %}

    <form class="d-flex flex-column align-items-center w-100 mb-3" method="post" novalidate>
        <div class="col-6">
            {% csrf_token %}

            <!-- Name -->
            <div class="form-group">
                {{ form.name.label_tag }}

                {% if form.is_bound %}
                    {% if form.name.errors %}
                        {% render_field form.name class="form-control is-invalid" %}
                        {% for error in form.name.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.name class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.name class="form-control" %}
                {% endif %}

                {% if form.name.help_text %}
                    <small class="form-text text-muted">
                        {{ form.name.help_text }}
                    </small>
                {% endif %}
            </div>

            <!-- Baseline (tempo only) -->
            <div class="form-group">
                {{ form.baseline.label_tag }}

                {% if form.is_bound %}
                    {% if form.baseline.errors %}
                        {% render_field form.baseline class="form-control is-invalid" %}
                        {% for error in form.baseline.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.baseline class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.baseline class="form-control" %}
                {% endif %}

                {% if form.baseline.help_text %}
                    <small class="form-text text-muted">
                        {{ form.baseline.help_text }}
                    </small>
                {% endif %}
            </div>

            <!-- Add (tempo only) -->
            <div class="form-group">
                {{ form.add.label_tag }}

                {% if form.is_bound %}
                    {% if form.add.errors %}
                        {% render_field form.add class="form-control is-invalid" %}
                        {% for error in form.add.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.add class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.add class="form-control" %}
                {% endif %}

                {% if form.add.help_text %}
                    <small class="form-text text-muted">
                        {{ form.add.help_text }}
                    </small>
                {% endif %}
            </div>

            <!-- Month (sancto only) -->
            <div class="form-group">
                {{ form.month.label_tag }}

                {% if form.is_bound %}
                    {% if form.month.errors %}
                        {% render_field form.month class="form-control is-invalid" %}
                        {% for error in form.month.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.month class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.month class="form-control" %}
                {% endif %}

                {% if form.month.help_text %}
                    <small class="form-text text-muted">
                        {{ form.month.help_text }}
                    </small>
                {% endif %}
            </div>

            <!-- Day (sancto only) -->
            <div class="form-group">
                {{ form.day.label_tag }}

                {% if form.is_bound %}
                    {% if form.day.errors %}
                        {% render_field form.day class="form-control is-invalid" %}
                        {% for error in form.day.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.day class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.day class="form-control" %}
                {% endif %}

                {% if form.day.help_text %}
                    <small class="form-text text-muted">
                        {{ form.day.help_text }}
                    </small>
                {% endif %}
            </div>

            <!-- Header -->
            <div class="form-group">
                {{ form.header.label_tag }}

                {% if form.is_bound %}
                    {% if form.header.errors %}
                        {% render_field form.header class="form-control is-invalid" %}
                        {% for error in form.header.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.header class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.header class="form-control" %}
                {% endif %}

                {% if form.header.help_text %}
                    <small class="form-text text-muted">
                        {{ form.header.help_text }}
                    </small>
                {% endif %}
            </div>

            <!-- Body -->
            <div class="form-group">
                {{ form.body.label_tag }}

                {% if form.is_bound %}
                    {% if form.body.errors %}
                        {% render_field form.body class="form-control is-invalid" %}
                        {% for error in form.body.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.body class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.body class="form-control" %}
                {% endif %}

                {% if form.body.help_text %}
                    <small class="form-text text-muted">
                        {{ form.body.help_text }}
                    </small>
                {% endif %}
            </div>

            <!-- Force -->
            <div class="form-group">
                {{ form.force.label_tag }}

                {% if form.is_bound %}
                    {% if form.force.errors %}
                        {% render_field form.force class="form-control is-invalid" %}
                        {% for error in form.force.errors %}
                            <div class="invalid-feedback" style="display: block;">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.force class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.force class="form-control" %}
                {% endif %}

                {% if form.force.help_text %}
                    <small class="form-text text-muted">
                        {{ form.force.help_text }}
                    </small>
                {% endif %}
            </div>
        </div>

        <div>
            <button type="submit" class="btn btn-primary">Validate</button>
        </div>
    </form>
{% endblock content %}

ordomatic/apps/days/templates/days/home.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'calendars:calendars_list' %}>Calendars</a></li>
    <li class="breadcrumb-item"><a href={% url 'calendars:calendar_details' calendar.pk %}>{{ calendar }}</a></li>
    <li class="breadcrumb-item active">Days</li>
{% endblock breadcrumbs %}

{% block content %}
    <h1>Days of calendar {{ calendar }}</h1>

    <a href={% url 'days:days_list' calendar.pk 'tempo' %}>Tempo</a>
    <a href={% url 'days:days_list' calendar.pk 'sancto' %}>Sancto</a>
{% endblock content %}

ordomatic/apps/days/templates/days/list_sancto.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'calendars:calendars_list' %}>Calendars</a></li>
    <li class="breadcrumb-item"><a href={% url 'calendars:calendar_details' calendar.pk %}>{{ calendar }}</a></li>
    <li class="breadcrumb-item"><a href={% url 'days:home' calendar.pk %}>Days</a></li>
    <li class="breadcrumb-item active">Sancto</li>
{% endblock breadcrumbs %}

{% block content %}
    <h1>{{ category|title }}</h1>
    <a href={% url 'days:day_create' calendar.pk 'sancto' %}>Create a new day</a>

    <table class="table table-sm table-bordered">
        <thead>
            <tr>
                <th class="text-center">Month</th>
                <th class="text-center">Day</th>
                <th class="text-center">Name</th>
                <th class="text-center">Header</th>
                <th class="text-center">Force</th>
            </tr>
        </thead>

        <tbody>
            {% for day in days %}
                <tr>
                    <td class="col-1">{{ day.month }}</td>
                    <td class="col-1">{{ day.day }}</td>
                    <td class="col-3">{{ day.name }}</td>
                    <td class="col-3">{{ day.header }}</td>
                    <td class="col-3">{{ day.force }}</td>
                    <td class="col-1">
                        <a href={% url 'days:day_details' calendar.pk 'sancto' day.pk %}>
                            <span class="fas fa-eye" title="See details of this day"></span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

ordomatic/apps/days/templates/days/list_tempo.html
{% extends 'main.html' %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href={% url 'calendars:calendars_list' %}>Calendars</a></li>
    <li class="breadcrumb-item"><a href={% url 'calendars:calendar_details' calendar.pk %}>{{ calendar }}</a></li>
    <li class="breadcrumb-item"><a href={% url 'days:home' calendar.pk %}>Days</a></li>
    <li class="breadcrumb-item active">Tempo</li>
{% endblock breadcrumbs %}

{% block content %}
    <h1>{{ category|title }}</h1>
    <a href={% url 'days:day_create' calendar.pk 'tempo' %}>Create a new day</a>

    <table class="table table-sm table-bordered">
        <thead>
            <tr>
                <th class="text-center">Name</th>
                <th class="text-center">Header</th>
                <th class="text-center">Force</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            {% for day in days %}
                <tr>
                    <td class="col-3">{{ day.name }}</td>
                    <td class="col-3">{{ day.header }}</td>
                    <td class="col-3">{{ day.force }}</td>
                    <td class="col-1">
                        <a href={% url 'days:day_details' calendar.pk 'tempo' day.pk %}>
                            <span class="fas fa-eye" title="See details of this day"></span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}